Revert "Change else if to switch"
This reverts commit af040122c88424ce39aa96b61cad30e2b426cbd4.

Got this from jack:
ERROR: /home/meticulus/android/CodinalteParts/src/com/meticulus/codinalteparts/app/MainActivity.java:121: Cannot switch on a value of type ImageView. Only convertible int values, strings or enum variables are permitted
ERROR: /home/meticulus/android/CodinalteParts/src/com/meticulus/codinalteparts/app/MainActivity.java:150: Cannot switch on a value of type Switch. Only convertible int values, strings or enum variables are permitted

When I wrote this, it was in Sun java 6 and then you could only switch on int.